### ISSUE TITLE
Error when Resizing Image greater than superview

### ISSUE THREAD

**Issue by sunlyear** [zedoul/ZDStickerView#10]
I got an error when trying to resize image greater than my superview. I just can't move, delete, or resize it back. 

Suggested solution: I guess you should keep checking if ZDStickerView instance is greater than its superview. If yes, do not allow to scale up. It is just my idea, and I am looking forward to seeing your updates. 

Anyway, I am appreciated all your hard working. I love your framework a lot. :)

**Comment by zedoul** [comment]
Hi sunlyear,

Thank you for your feedback and I am so sorry for my late response. 

The root cause is because iOS do not directly send any button event to subview outside the frame of its superview. So in this case, the UI library can not handle this situation.

One solution to cover this problem is to iterate its subviews and give the event to proper subview. We can use this indirect approach as far as I know. See [this post](http://stackoverflow.com/questions/11770743/capturing-touches-on-a-subview-outside-the-frame-of-its-superview-using-hittest) as an example.

Apart from that, I would provide a sample that could handle ZDStickerView outside of its superview since it would help others :)

**Comment by ahsanebrahim** [comment]
Solved this problem by globally storing my parentView's width and height and then putting this condition in resizing before changing the bounds

if (((self.bounds.size.width + (wChange)) < (parentViewWidth - (parentViewWidth/4))) && ((self.bounds.size.height + (hChange)) < (parentViewHeight - (parentViewHeight/4))))
