### ISSUE TITLE
Not working on uiimageview

### ISSUE THREAD

**Issue by badalpub1991** [zedoul/ZDStickerView#14]
It is not working on Imageview. Means when we add zdstickerview to image then we can't able to move . How can i make it work ?

**Comment by zedoul** [comment]
Hello, thank you for letting me know the issue. Let me have one question to get to know of this issue more clearly: the sample application (https://github.com/zedoul/ZDStickerView/blob/master/ZDStickerViewApp/ZDStickerViewApp/ViewController.m) shows that ZDStickerView can control UIImageView object, and I checked it works. 

Can you let me know how you create ZDStickerView to reproduce the bug?

**Comment by badalpub1991** [comment]
Hey Buddy !
  Thank you for replay. You are really helpful. Here i have attached demo. In this demo i can not able to move sticker. Thank you again.

http://s000.tinyupload.com/index.php?file_id=07385137336951193147

**Comment by zedoul** [comment]
Hello,

First of all, let's make it sure first that it is NOT a ZDStickerView issue. It is a matter of *user interaction flag* problem. It is very hard to explain in this issue. It is a pretty basic concept that you can learn from any iOS dev book. Let me give you a hint: check *the view* as a container, then you can see it is flagged as `false`, which is supposed be flagged as `true`. 

You want to have a quick solution? then use 

    [self.view addSubview:userResizableView1] 

instead of previous code. Then you will see it works.

You are allowed to ask any question in this board, however, Google or Stackoverflow may be your first stop for any obvious questions.
